"""
Chronopoli Partner Dashboard — Views

Analytics, intelligence reports, talent pipeline metrics for partners.
"""

import logging

from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_GET

from .models import Partner

logger = logging.getLogger(__name__)


@login_required
def partner_dashboard(request, slug):
    """
    Main partner dashboard — enrollment trends, completion rates,
    badge counts, intelligence reports.
    """
    partner = get_object_or_404(Partner, slug=slug, is_active=True)

    # Basic access control: partner contact email or staff
    if not request.user.is_staff and request.user.email != partner.contact_email:
        return render(request, "chronopoli/partners/access_denied.html", status=403)

    context = {
        "partner": partner,
        "stats": _get_partner_stats(partner),
    }
    return render(request, "chronopoli/partners/dashboard.html", context)


@login_required
@require_GET
def api_analytics(request, slug):
    """JSON analytics data for Chart.js."""
    partner = get_object_or_404(Partner, slug=slug, is_active=True)

    if not request.user.is_staff and request.user.email != partner.contact_email:
        return JsonResponse({"error": "Access denied"}, status=403)

    stats = _get_partner_stats(partner)
    return JsonResponse(stats)


@login_required
@require_GET
def api_intelligence_reports(request, slug):
    """
    Return intelligence reports from Symposia pipeline for this partner.
    Reports are stored in S3, referenced by partner slug.
    """
    partner = get_object_or_404(Partner, slug=slug, is_active=True)

    if not request.user.is_staff and request.user.email != partner.contact_email:
        return JsonResponse({"error": "Access denied"}, status=403)

    reports = _get_intelligence_reports(partner)
    return JsonResponse({"reports": reports})


def _get_partner_stats(partner):
    """
    Compute enrollment, completion, and badge statistics for a partner.
    """
    stats = {
        "total_tracks": 0,
        "total_enrollments": 0,
        "total_completions": 0,
        "total_badges": 0,
        "total_job_applications": 0,
        "completion_rate": 0,
        "tracks": [],
    }

    try:
        tracks = partner.tracks.filter(is_published=True)
        stats["total_tracks"] = tracks.count()

        for track in tracks:
            track_stats = {
                "name": track.name,
                "course_key": track.course_key,
                "enrollments": 0,
                "completions": 0,
            }

            # Try to get enrollment counts from OpenEdX
            try:
                from common.djangoapps.student.models import CourseEnrollment
                from opaque_keys.edx.keys import CourseKey

                key = CourseKey.from_string(track.course_key)
                track_stats["enrollments"] = CourseEnrollment.objects.filter(
                    course_id=key, is_active=True,
                ).count()
                stats["total_enrollments"] += track_stats["enrollments"]
            except (ImportError, Exception):
                pass

            stats["tracks"].append(track_stats)

        # Badge counts (if academy app is installed)
        try:
            from chronopoli_academy.models import UserBadge

            stats["total_badges"] = UserBadge.objects.filter(
                badge__partner=partner,
            ).count()
        except (ImportError, Exception):
            pass

        # Job application counts
        try:
            from chronopoli_academy.models import JobApplication

            stats["total_job_applications"] = JobApplication.objects.filter(
                job__partner=partner,
            ).count()
        except (ImportError, Exception):
            pass

        if stats["total_enrollments"] > 0:
            stats["completion_rate"] = round(
                (stats["total_completions"] / stats["total_enrollments"]) * 100, 1
            )

    except Exception as e:
        logger.error("Error computing partner stats for %s: %s", partner.slug, e)

    return stats


def _get_intelligence_reports(partner):
    """
    Retrieve intelligence reports generated by the Symposia pipeline.
    """
    reports = []
    try:
        from chronopoli_symposia.models import RoundTableOutput

        outputs = RoundTableOutput.objects.filter(
            output_type="partner_report",
            status__in=["approved", "published"],
        ).select_related("round_table").order_by("-created_at")[:20]

        for output in outputs:
            # Check if this report mentions the partner
            # (In production, partner_reports.json contains per-partner sections)
            reports.append({
                "round_table_title": output.round_table.title,
                "s3_key": output.s3_key,
                "generated_at": output.generated_at.isoformat() if output.generated_at else None,
                "status": output.status,
            })
    except (ImportError, Exception) as e:
        logger.warning("Could not fetch intelligence reports: %s", e)

    return reports
